#Denna är lite mer komplex
version: "3.4"
services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: "hass"
    depends_on:
      - mqtt
      - influxdb
    volumes:
#      - /home/$USER/.homeassistant:/config
      - /home/$USER/src/dehydrated:/home/pi/src/dehydrated
      - /etc/localtime:/etc/localtime:ro
#      - /dev/serial/by-id/usb-1234_5678-ff00:/dev/serial/by-id/usb-1234_5678-ff00
      - /home/$USER/docker_files/homeassistant/:/config
    privileged: true
    network_mode: host

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: "MQTT"
    restart: unless-stopped
    volumes:
      - /home/$USER/.homeassistant/mqtt/config:/mqtt/config:ro
      - /home/$USER/.homeassistant/mqtt/data:/mqtt/data
      - /home/$USER/.homeassistant/mqtt/passwd:/mqtt/passwd
      - /home/$USER/src/dehydrated/certs:/mqtt/conf/certs
#      - ./config/mqtt:/mqtt/config
#      - ./log/mqtt:/mqtt/log
#      - ./data/mqtt:/mqtt/data/
#      - "/opt/containers/mqtt-mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
#      - "/opt/containers/mqtt-mosquitto/data:/mosquitto/data"
#      - "/opt/containers/mqtt-mosquitto/log:/mosquitto/log"
#      - /home/$USER/docker_files/mqtt/data:/mosquitto/data
#      - /home/$USER/docker_files/mqtt/config:/mosquitto/config
#      - /home/$USER/docker_files/mqtt/log:/mosquitto/log
#    user: "1000"
    ports:
      - 1883:1883
      - 9001:9001
#      - 9001:9001

  influxdb:
    image: influxdb:latest
    container_name: "influxdb"
    volumes:
#      - /mnt/influxdb:/data
    # Data persistency
    # sudo mkdir -p /srv/docker/influxdb/data
    # sudo mkdir -p /home/$USER/docker_files/influxdb/data
#      - /srv/docker/influxdb/data:/var/lib/influxdb
      - /home/$USER/docker_files/influxdb/data:/var/lib/influxdb
    environment:
      PRE_CREATE_DB: "home-assistant"
    ports:
      - 8086:8086

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    container_name: "grafana"
    restart: unless-stopped
    depends_on:
      - influxdb
    volumes:
    # create /var/lib/grafana as persistent volume storage
    # sudo mkdir -p /var/lib/grafana
#      - /mnt/influxdb/grafana/etc:/etc/grafana
#      - /mnt/influxdb/grafana/data:/data
      - /home/$USER/docker_files/grafana/etc:/etc/grafana
      - /home/$USER/docker_files/grafana/data:/data
    ports:
      - 3000:3000

  appdaemon:
    image: acockburn/appdaemon:latest
    container_name: "appdaemon"
    volumes:
      - /home/pi/.homeassistant/appdaemon:/conf
      - /etc/localtime:/etc/localtime:ro
      - /home/$USER/src/dehydrated/certs/pi.duckdns.org/fullchain.pem:/var/certs/fullchain.pem:ro
      - /home/$USER/src/dehydrated/certs/pi.duckdns.org/privkey.pem:/var/certs/privkey.pem:ro
#      - /home/$USER/docker_files/mqtt/data:/mosquitto/data
#      - /home/$USER/docker_files/mqtt/config:/mosquitto/config
#      - /home/$USER/docker_files/mqtt/log:/mosquitto/log
    ports:
      - 5050:5050
      - 5000:5000